## use NANO as default editor in terminal
export EDITOR="nano";

## Change prompt layout
zstyle ':prompt:grml:left:setup' items rc change-root user at host path vcs newline percent

## Change "%" to "$"
zstyle ':prompt:grml:left:items:percent' token '$ '

## Change token color
zstyle ':prompt:grml:left:items:path' pre  '%B%F{white}'
zstyle ':prompt:grml:left:items:path' post '%f%b'

source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
